config/routes.rb
Rails.application.routes.draw do
  resources :portfolios
  resources :trackings
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/etf.rb
class Etf < ApplicationRecord
  has_many :trackings
  has_many :portfolios, through: :trackings
  has_many :constituents, class_name: 'EtfConstituent', dependent: :destroy
end

app/models/etf_constituent.rb
class EtfConstituent < ApplicationRecord
  belongs_to :etf
  has_many :prices, dependent: :destroy

  accepts_nested_attributes_for :prices

  def price
    prices.order(created_at: :desc).limit(1).first
  end
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :trackings
  has_many :etfs, through: :trackings
end

app/models/price.rb
class Price < ApplicationRecord
  belongs_to :etf_constituent
end

app/models/tracking.rb
class Tracking < ApplicationRecord
  belongs_to :etf
  belongs_to :portfolio
end

app/models/trade.rb
class Trade < ApplicationRecord
  self.inheritance_column = :_not_used # Overwrite default :type to avoid it being used by rails for STI

  belongs_to :etf_constituent
  belongs_to :tracking
  has_one :etf, through: :tracking
  has_one :portfolio, through: :tracking

  scope :buys, ->(constituent) { where(type: :buy, etf_constituent: constituent) }
  scope :sells, ->(constituent) { where(type: :sell, etf_constituent: constituent) }

  def cost
    amount * price
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_raven_context

  def set_raven_context
    Raven.extra_context(params: params.to_unsafe_h, url: request.url)
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:show, :edit, :update, :destroy]

  def index
    @portfolios = Portfolio.all
  end

  def show
  end

  def new
    @portfolio = Portfolio.new
  end

  def edit
  end

  def create
    @portfolio = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully created.' }
        format.json { render :show, status: :created, location: @portfolio }
      else
        format.html { render :new }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @portfolio.update(portfolio_params)
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully updated.' }
        format.json { render :show, status: :ok, location: @portfolio }
      else
        format.html { render :edit }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @portfolio.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portfolio
      @portfolio = Portfolio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def portfolio_params
      params.require(:portfolio).permit(:name, etf_ids: [])
    end
end

app/controllers/trackings_controller.rb
class TrackingsController < ApplicationController
  def edit
    @tracking = Tracking.find(params[:id])
    @etf = @tracking.etf
  end
end

app/views/layouts/application.slim
doctype html
html
  head
    title
      | EtfBasket
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag    'application', 'data-turbolinks-track': 'reload'
    meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"
  body.bg-light
    .container
      = yield

app/views/portfolios/_form.html.slim
.col-md-8
  = form_for @portfolio do |f|
    - if @portfolio.errors.any?
      #error_explanation
        h2 = "#{pluralize(@portfolio.errors.count, "error")} prohibited this portfolio from being saved:"
        ul
          - @portfolio.errors.full_messages.each do |message|
            li = message

    .field.mb-3
      = f.label :name
      = f.text_field :name, class: 'form-control'
    .field.mb-3
      = f.label :etf
      = f.collection_select :etf_ids, Etf.all, :id, :name, {}, {class: 'custom-select', multiple: true}
    hr.mb-4
    .actions = f.submit submit_label, role: 'button', class: 'btn btn-primary'

app/views/portfolios/edit.html.slim
h1 Editing portfolio

== render 'form', submit_label: 'Update'

=> link_to 'Show', @portfolio
'|
=< link_to 'Back', portfolios_path

app/views/portfolios/index.html.slim
.py-5.text-center
  h1 Listing portfolios

.row
  .col-md-8
    table.table.table-striped.table-sm
      thead
        tr
          th Name
          th
          th
          th

      tbody
        - @portfolios.each do |portfolio|
          tr
            td = portfolio.name
            td = link_to 'Show', portfolio
            td = link_to 'Edit', edit_portfolio_path(portfolio)
            td = link_to 'Destroy', portfolio, data: { confirm: 'Are you sure?' }, method: :delete
.col-md-8
  .row
    br
    = link_to 'New Portfolio', new_portfolio_path, role: 'button', class: 'btn btn-primary'

app/views/portfolios/new.html.slim
.py-5.text-center
  h1 New portfolio

.row
  == render 'form', submit_label: 'Create'
.row
  = link_to 'Back', portfolios_path

app/views/portfolios/show.html.slim
p#notice = notice

.py-5.text-center
  h1= @portfolio.name
  h3 Trackings

.row
  .col-md-8
    table.table.table-striped.table-sm
      thead
        tr
          th Name
          th Symbol
          th
          th

      tbody
        - @portfolio.trackings.each do |tracking|
          tr
            td = tracking.etf.symbol
            td = tracking.etf.name
            td = link_to 'Trade', edit_tracking_path(tracking)
            td = link_to 'Destroy', @portfolio, data: { confirm: 'Are you sure?' }, method: :delete
.col-md-8
  .row

=> link_to 'Edit', edit_portfolio_path(@portfolio)
'|
=< link_to 'Back', portfolios_path

app/views/trackings/edit.html.slim
p#notice = notice

.py-5.text-center
  h1= "#{@etf.name} in #{@tracking.portfolio.name}"
  h3 Constituents

.row
  .col-md-8
    table.table.table-striped.table-sm
      thead
        tr
          th Name
          th Symbol
          th Weight
          th Owned (count)
          th Shares (%)
          th Cost
          th Value
          th Actions

      tbody
        - @etf.constituents.each do |constituent|
          - summarizer = TradesSummarizer.new(constituent, @tracking)
          tr
            td = constituent.name
            td = constituent.symbol
            td = constituent.weight
            td = summarizer.owned_count
            td = summarizer.owned_weight
            td = summarizer.cost
            td = summarizer.value
            td
              div = link_to 'Buy', edit_tracking_path(@tracking)
              div = link_to 'Sell', edit_tracking_path(@tracking)
.col-md-8
  .row

=< link_to 'Back to portfolio', portfolio_path(@tracking.portfolio)